# Generated by Django 3.1.2 on 2020-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ph_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
