# Generated by Django 3.1.2 on 2020-10-28 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201017_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.CharField(max_length=50)),
                ('msg_to', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'msg_bulk',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
